# age:int=int(input("what is your age"))
a:int=int(input("Enter number 1"))
b:int=int(input("Enter number 1"))
c:int=int(input("Enter number 1"))
d:int=int(input("Enter number 1"))
e:int=int(input("Enter number 1"))
total:float=float((a+b+c+d+e)/5)
print(f"the total is {total:.2f}")